[package]
name = "odido-aap"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "odido"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1"
chrono = { version = "0.4.43", default-features = false, features = ["clock"] }
clap = { version = "4.5.54", features = ["derive", "env"] }
dirs = "6.0"
http-body = "1.0.1"
owo-colors = "4.2.3"
reqwest = { version = "0.13.1", features = ["json", "gzip", "brotli"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.49.0", features = [
  "rt-multi-thread",
  "macros",
  "signal",
] }
tower-http = { version = "0.6.8", features = ["trace"] }
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.22", features = [
  "env-filter",
  "fmt",
  "ansi",
] }

[dev-dependencies]
tempfile = "3.24"
